### ISSUE TITLE
Increment numbers in the wrong way

### ISSUE THREAD

**Issue by arnaudambro** [albymor/Increment-Selection#1]
Hello,
I want to use your simple extension, but it increases my number not increasingly, but decreasingly, is it the same for you ?
I looked at your code, I see your code for letters but I don't see it for numbers, so I don't know how I can change it...

Thanks !

**Comment by arnaudambro** [comment]
Sorry, I just see where it is.
I try to modify it...

**Comment by albymor** [comment]
Hello,
the behavior of the extension depends on how you do the multiple selection. If you get a numbering contrary to what you want, try reversing the multiple selection.

In other words, if you want an increasing numbering (as in the GIF in readme.md) you have to make a "top-down" selection while if you want a descending numbering you have to make a "bottom-up" selection.

I don't know if I explained myself.
Let me know

**Comment by arnaudambro** [comment]
Yes that's what I just figured out. It's not the same behavior as the extension in ST3, that's why I was confused. I'll have to change a bit my habits, that's all !
Thanks
