### ISSUE TITLE
The possibility of increasing from 1 instead of 0

### ISSUE THREAD

**Issue by kanlukasz** [albymor/Increment-Selection#13]
Hello
Can you add option that will allow set the increase option from 1 instead of 0?
It would be awesome

By the way - great add-on! 🥇 
Thank you

**Comment by albymor** [comment]
Hi,
thank you for the feedback!!

You can increase starting from 1 by placing a multi cursor then write 1 and finally increment the selection.
![from1](https://user-images.githubusercontent.com/19717991/79358950-37dcae80-7f42-11ea-81c5-e58398944cea.gif)

Maybe in the next release, I will add an option to select the default starting number, but first I have to check if it breaks something in letters support.

I leave the issue open and label it as enhancement.
