### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mattez** [albymor/Increment-Selection#15]
Hi, I have no idea why. But `Increment Selection` v.0.2.0 do nothing in my last version of VSC on Ubuntu.
I have tried almost everything.  New file, saved file, start with `0` start with `1`. Nothing happens.
Any help welcome.
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z (4 days ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-123-generic
```

**Comment by mattez** [comment]
A `disabled` and `re-enabled` Increment Selection extension and restart VSCode.
**It works now.**

Thank you for this great helpfull extension.

**Comment by albymor** [comment]
Hi, I'm glad you solved the problem. I tried to reproduce it but I had no luck.

Anyway, if you note something strange, feel free to reopen the issue.
