### ISSUE TITLE
Incrementing by Letters

### ISSUE THREAD

**Issue by smhmd** [albymor/Increment-Selection#4]
![image](https://user-images.githubusercontent.com/46059092/55733456-c7897c00-5a15-11e9-96df-f7ee2e514826.png)
why is it increment by letters not numbers and doesn't include the first selection? is there a setting to change this?

**Comment by albymor** [comment]
Ok i was able to recreate the bug: from what I could see, you're trying to increment the selection without first selecting a letter or number. This leads to an unhandled condition where the increment occurs by letter excluding the first cursor.

When nothing is selected, I will set the increment by number starting from zero as the default behavior.

For now the workaround is to put the number (or letter) from which you want to start, select it and than Ctrl + Alt + I to increment the selection (see gif below).

![how_to](https://user-images.githubusercontent.com/19717991/55741248-1c84bc80-5a2d-11e9-9897-2a833136507d.gif)

**Comment by smhmd** [comment]
@albymor could you also keep the structure? 
![image](https://user-images.githubusercontent.com/46059092/55743733-feb65800-5a2a-11e9-954f-42d5ba05e36c.png)
000 => 001 and so on?
