### ISSUE TITLE
Increment and decrement not keeping leading zero

### ISSUE THREAD

**Issue by albymor** [albymor/Increment-Selection#5]
@albymor could you also keep the structure? 
![image](https://user-images.githubusercontent.com/46059092/55743733-feb65800-5a2a-11e9-954f-42d5ba05e36c.png)
000 => 001 and so on?

_Originally posted by @alivefromupstairs in https://github.com/albymor/Increment-Selection/issues/4#issuecomment-480924170_

**Comment by BrianDevKit** [comment]
Doesn't appear to be base 10.

![IncrementSelection](https://user-images.githubusercontent.com/51457281/61001782-4a301900-a32e-11e9-84b0-9f1e4be1fb1d.PNG)
